version: '3'
services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
    environment:
      DATABASE_URL: mysql://dbinstance:avenged7fold@instancedb.c5dwfvkkl6tn.us-east-1.rds.amazonaws.com/kanboard
